### ISSUE TITLE
Freeze server

### ISSUE THREAD

**Issue by NycuRO** [AnkitM252/CombinedSlots#3]
Plugin not work.

Probably website problem. You can fix @AnkitM252 ?

**Comment by NycuRO** [comment]
Fixed.

**Comment by NycuRO** [comment]
Latest version get freeze server on Tesseract.

**Comment by AnkitM252** [comment]
Does it freeze on startup and runs smoothly after that?

**Comment by NycuRO** [comment]
Runs.

**Comment by AnkitM252** [comment]
Explain!

**Comment by akaSnapy** [comment]
You have to explain the error, I don't have any problems with it.

**Comment by AnkitM252** [comment]
I think it slows at the startup and runs normal after that!

**Comment by NycuRO** [comment]
If i start server ( i'm added more server is offline ), wait 3~5 sec and get freeze.

OS: Windows 10 Pro
Hosting: Ubuntuu 14.04.5 LTS 64bit
PHP: 7.0.15

**Comment by akaSnapy** [comment]
hmm, are those servers on the same ip?

**Comment by AnkitM252** [comment]
This doesn't happens with me but instead it freezes for 2-5 sec (on my local pc which is not so good) but runs smoothly after that!

**Comment by NycuRO** [comment]
@akaSnapy yes

**Comment by NycuRO** [comment]
@AnkitM252 For me freeze totaly.

**Comment by AnkitM252** [comment]
Where is it hosted? HomePC? VPS?

**Comment by NycuRO** [comment]
VPS

**Comment by akaSnapy** [comment]
@NycuRO use tesseract.yml, then scroll down and use this settings. Its same as combinedslots.
dserver:
 #This setting decides if the server counts all multi-servers combined
 #If you do not know what this does, keep it set to "false"
 enable: false
 #This setting decides if the server will automatically update the Query
 query-auto-update: false
 #This setting decides if the server Query ticks update
 query-tick-update: true
 #This setting displays the # of max players on MOTD. 0 = Default
 motd-max-players: 0
 #This setting displays the # of max players on Query. 0 = Default
 query-max-players: 0
 #This setting decides if the server shows the # of all players on MOTD
 motd-all-players: false
 #This setting shows the number of all players on Query
 query-all-players: false
 #This setting shows the number of online players on MOTD
 motd-players: false
 #This setting shows the number of online players on Query
 query-players: false
 #This setting decides the interval for query/motd updating. 20=1s
 time: 40
 #This setting decides the # of times the server retries when the server fails to load. 0 = Disable, 3 = Default
 retry-times: 3
 #This setting displays the server list，Separate by ';'，e.g. 1.example.com:19132;2.example.com:19133
 server-list: ""

**Comment by NycuRO** [comment]
Ok @akaSnapy

**Comment by akaSnapy** [comment]
Hopefully helped u @NycuRO
